### ISSUE TITLE
guess

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/guess#1]
![es5_35](https://cloud.githubusercontent.com/assets/3002194/19112992/ef7a32de-8b07-11e6-8929-e7dcc6faf2eb.png)

**Comment by TeoColuccio** [comment]
Bugga quando deve ripetere il tutto. Dopo vedo di aggiustare, per il resto dovrebbe andare bene.

**Comment by FabioZTessitore** [comment]
mi rifiuto di leggere il codice. dove sono i moduli?

**Comment by TeoColuccio** [comment]
Ok lo modifico, ma non è poi tanto complesso da richiedere i moduli

**Comment by TeoColuccio** [comment]
Funziona la prima volta e poi bugga. Ma come mai entra nel secondo do while però mi salta la scanf?

**Comment by TeoColuccio** [comment]
Per favore metteteci le mani voi nel mio ciclo difettoso, perchè ho provato ad usare getchar() ma è la stessa cosa..

**Comment by FabioZTessitore** [comment]
bastava guardare quello che ti avevo mandato
