### ISSUE TITLE
Contatore tentativi

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/guess#2]
![es5_36](https://cloud.githubusercontent.com/assets/3002194/19192992/890bbac0-8ca8-11e6-9ca9-febb004f26a4.png)

**Comment by TeoColuccio** [comment]
Ok il programma l'ho fatto. 
Per quanto riguarda il ragionamento: Servono 10 o meno tentativi perchè il primo sarà sicuro 500, in base alla risposta tenteremo con 1/4 (cioè 250) o 3/4 (ovvero 750) e così via.. Bisognerà insomma "tentare" sempre la metà tra i due limiti per avvicinarci sempre più.
